---
title: "Applying to Grad School"
---

Advice on the PhD application process, from choosing programs to writing your statement of purpose.

- [Chris Blattman: Application Advice](https://af4.cf3.mwp.accessdomain.com/about/contact/gradschool/)
- [Berkeley: Advice on Statements of Purpose](https://grad.berkeley.edu/admissions/steps-to-apply/requirements/statement-purpose/)
- [Susan Athey: Professional Advice](https://gsb-faculty.stanford.edu/susan-athey/professional-advice/)
  — Includes guidance on applying to PhD programs and choosing advisors.
- [Miles Kimball: The Complete Guide to Getting into an Economics PhD Program](https://qz.com/116081/the-complete-guide-to-getting-into-an-economics-phd-program/)
- [Elgin et al.: So You Want to Go to Grad School in Economics?](https://drive.google.com/file/d/1KryQkyfcSBDLIY6XKVtcyvp8mv5wrOoZ/view)
- [Rachael Meager: For the Ambitious, Prospective Ph.D. Student](https://economics.com.au/2012/03/27/for-the-ambitious-prospective-phd-student-a-guide/)
- [Natalie Duncombe: Applying to Graduate School (Slides)](https://natalieduncombe.files.wordpress.com/2020/08/applying-to-graduate-school-2.pptx)
- [Natalie Duncombe: Preparing for the NSF (Slides)](https://natalieduncombe.files.wordpress.com/2020/08/preparing-for-the-nsf-1.pptx)
- [Alex Lang: NSF GRFP Guide](https://www.alexhunterlang.com/nsf-fellowship)
  — Detailed guide to the NSF Graduate Research Fellowship Program.
- [Shiv Hastawala: Advice for PhD Econ Aspirants from India](https://www.shivhastawala.com/resources/econ-phd-us-india)
- [Jesse Shapiro: Notes on Applying for a PhD in Economics](https://scholar.harvard.edu/files/shapiro/files/phdnotes.pdf)
- [Harvard-MIT Application Assistance and Mentoring Program (AAMP)](https://economics.mit.edu/academic-programs/phd-program/admissions)
- [LSE Applicant Mentoring Program](https://sites.google.com/view/econphdamp/home)
